name: Test Workflows

on:
  workflow_dispatch:

jobs:
  generate-changelog:
    uses: soup-bowl/wordpress-workflows/.github/workflows/generate-changelog.yml@main
    with:
      repository: soup-bowl/wp-simple-smtp
    secrets: inherit

  check-log:
    runs-on: ubuntu-latest
    needs: generate-changelog
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update Readme
        run: |
          echo "== Changelog ==" > readme.txt
          echo "${{ needs.generate-changelog.outputs.changelog }}" | base64 --decode > readme.txt
          cat readme.txt

      - name: Check Log
        run: cat readme.txt
